name: C++ CI for hello_world

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install C++ Compiler
      run: sudo apt-get install -y g++

    - name: Compile hello_world.cpp
      run: g++ hello_world.cpp -o hello_world

    - name: Run hello_world
      run: ./hello_world
